### PR TITLE
Fix ParseNew to be compatible with NHibernate.Linq...

### PR DESCRIPTION
**Pull request by jehhynes**
...and don't blow up trying to reflect types on bad assemblies.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @jehhynes,

First of all thanks for your contribution!

Before we will continue to review + merge, can you provide a bit more information about the issues you were fixing? 

- Maybe you remember what assemblies were throwing `ReflectionTypeLoadException`?
- Can you provide a bit more details about why we need to have a constructor on dynamic type? Maybe you can create a unit-test to illustrate the issue?

**Comment by jehhynes** [comment]
1. The ReflectionTypeLoadException is coming from an obfuscated assembly (details below). It's my understanding that component libraries (such as ActiveReports) obfuscate their assemblies which can cause issues when reflecting. We don't want DynamicLinq to fail entirely just because the AppDomain happens to have an assembly such as this loaded.

```
ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
LoaderExceptions:
-		[0]	{"Could not load type '#ZNA.#0Ug' from assembly 'GrapeCity.ActiveReports.Export.Excel.v7, Version=7.2.7725.0, Culture=neutral, PublicKeyToken=cc4967777c49a3ff' because it contains an object field at offset 100 that is incorrectly aligned or overlapped by a non-object field.":"#ZNA.#0Ug"}	System.Exception {System.TypeLoadException}
-		[1]	{"Could not load type '#ZNA.#Fpc' from assembly 'GrapeCity.ActiveReports.Export.Excel.v7, Version=7.2.7725.0, Culture=neutral, PublicKeyToken=cc4967777c49a3ff' because it contains an object field at offset 76 that is incorrectly aligned or overlapped by a non-object field.":"#ZNA.#Fpc"}	System.Exception {System.TypeLoadException}
```

2. It would be involved to create a unit test for NHibernate queries, and since you currently don't have any tests for NHibernate, I'm not sure I want to do that now. However, to give you an idea of the issue - Without the mods in this PR, I'm getting an error running a query such as the following:

`query.GroupBy("new ( it.Property1 as XValue )", "it").Select($"new ( it.Key, it.Sum(Property2) as YValue )")`

(Note that the portion of concern is the Select. The GroupBy works fine)
The following exception is generated:

```
[NotSupportedException: MemberInit]
   NHibernate.Linq.Visitors.HqlGeneratorExpressionVisitor.VisitExpression(Expression expression) +1307
```

This answer on StackOverflow explains why: https://stackoverflow.com/a/56118417/373482

If you look at the lambda expression generated by DynamicLinq, the portion of concern looks like:

```
.Lambda #Lambda4<System.Func`2[System.Linq.IGrouping`2[DynamicClass1,Drg.M3.Domain.QA.Audit],DynamicClass2]>(System.Linq.IGrouping`2[DynamicClass1,Drg.M3.Domain.QA.Audit] $var4)
{
    .New DynamicClass2(){
        Key = $var4.Key,
        YValue = .Call System.Linq.Enumerable.Count($var4)
    }
}
```

Whereas, the equivalent expression, generated by compiled Linq, looks like:

```
.Lambda #Lambda3<System.Func`2[System.Linq.IGrouping`2[<>f__AnonymousType0`2[System.String,System.Boolean],Drg.M3.Domain.QA.Audit],<>f__AnonymousType1`2[<>f__AnonymousType0`2[System.String,System.Boolean],System.Int32]]>(System.Linq.IGrouping`2[<>f__AnonymousType0`2[System.String,System.Boolean],Drg.M3.Domain.QA.Audit] $x)
{
    .New <>f__AnonymousType1`2[<>f__AnonymousType0`2[System.String,System.Boolean],System.Int32](
        $x.Key,
        .Call System.Linq.Enumerable.Count($x))
}
```

The difference is that DynamicLinq is calling the default constructor, and setting the values; whereas compiled Linq calls a constructor with parameters, passing in the property values as arguments.

The change that I made causes DynamicLinq to work consistently with how compiled Linq works. It also solves this error.

**Comment by ghost** [comment]
Thank you for information!

What version of framework are you on? Can you try whether assembly load exception is reproduced if we replace `x.GetTypes()` with `x.GetExportedTypes()`?

**Comment by jehhynes** [comment]
This is .NET Framework 4.6.1

x.GetExportedTypes() gives this error:
`Could not load file or assembly 'Microsoft.VisualStudio.Shell.9.0, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

It also causes some of the For35 tests to fail
```
Test Name:	Contains
Test FullName:	System.Linq.Dynamic.Tests.BasicTests.Contains
Test Source:	D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic.Tests\BasicTests.cs : line 121
Test Outcome:	Failed
Test Duration:	0:00:00.1194379

Result StackTrace:	
at System.Reflection.Emit.InternalAssemblyBuilder.GetExportedTypes()
   at System.Linq.Dynamic.DefaultDynamicLinqCustomTypeProvider.<>c.<FindTypesMarkedWithAttribute>b__1_0(Assembly x) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\DynamicLinqTypeProvider.cs:line 31
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection)
   at System.Linq.Dynamic.DefaultDynamicLinqCustomTypeProvider.GetCustomTypes() in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\DynamicLinqTypeProvider.cs:line 47
   at System.Linq.Dynamic.ExpressionParser.CreateKeywords() in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\ExpressionParser.cs:line 2294
   at System.Linq.Dynamic.ExpressionParser..ctor(IDynamicLinkCustomTypeProvider provider, ParameterExpression[] parameters, String expression, Object[] values) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\ExpressionParser.cs:line 292
   at System.Linq.Dynamic.ExpressionParser..ctor(ParameterExpression[] parameters, String expression, Object[] values) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\ExpressionParser.cs:line 286
   at System.Linq.Dynamic.DynamicExpression.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\DynamicExpression.cs:line 15
   at System.Linq.Dynamic.DynamicExpression.ParseLambda(Type itType, Type resultType, String expression, Object[] values) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\DynamicExpression.cs:line 9
   at System.Linq.Dynamic.DynamicQueryable.Where(IQueryable source, String predicate, Object[] args) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\DynamicQueryable.cs:line 65
   at System.Linq.Dynamic.DynamicQueryable.Where[TSource](IQueryable`1 source, String predicate, Object[] args) in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic\DynamicQueryable.cs:line 34
   at System.Linq.Dynamic.Tests.BasicTests.Contains() in D:\git\System.Linq.Dynamic\Src\System.Linq.Dynamic.Tests\BasicTests.cs:line 129
Result Message:	
Test method System.Linq.Dynamic.Tests.BasicTests.Contains threw exception: 
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
```

**Comment by ghost** [comment]
Thank you for trying these things. I have no idea what to check more (it was so long ago when I was working with .NET 3.5 that I don't remember these old reflection tricks).

I have created a small [PR](https://github.com/jehhynes/System.Linq.Dynamic/pull/1) to you master branch with a few small changes to your code (if you merge it the changes will automatically reflect here).

**Comment by jehhynes** [comment]
Your commits have been merged in.

**Review by ghost — APPROVED** [review]

**Pull request merged**
